pipeline:
  dockerfile:
    image: alpine
    commands:
      - sed -i -e "s/latest/${TAG}/1" Dockerfile

  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/eve/debian
    tag: ${TAG}
    file: Dockerfile-${TAG}

  notify:
    image: no-cloud.fr/drone-xmpp
    secrets: [ xmpp_jid, xmpp_password, xmpp_to ]

matrix:
  TAG:
    - stable
    - sid
    - jessie
    - stretch
    - latest
    - unstable
